name: freezed_test_environment
channels:
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cmake=4.0.2
  - cuda=12.6.3
  - cuda-cccl=12.6.77
  - cuda-cccl_linux-64=12.6.77
  - cuda-command-line-tools=12.6.3
  - cuda-compiler=12.6.3
  - cuda-crt-dev_linux-64=12.6.85
  - cuda-crt-tools=12.6.85
  - cuda-cudart=12.6.77
  - cuda-cudart-dev=12.6.77
  - cuda-cudart-dev_linux-64=12.6.77
  - cuda-cudart-static=12.6.77
  - cuda-cudart-static_linux-64=12.6.77
  - cuda-cudart_linux-64=12.6.77
  - cuda-cuobjdump=12.6.77
  - cuda-cupti=12.6.80
  - cuda-cupti-dev=12.6.80
  - cuda-cuxxfilt=12.6.77
  - cuda-driver-dev=12.6.77
  - cuda-driver-dev_linux-64=12.6.77
  - cuda-gdb=12.6.77
  - cuda-libraries=12.6.3
  - cuda-libraries-dev=12.6.3
  - cuda-nsight=12.6.77
  - cuda-nvcc=12.6.85
  - cuda-nvcc-dev_linux-64=12.6.85
  - cuda-nvcc-impl=12.6.85
  - cuda-nvcc-tools=12.6.85
  - cuda-nvcc_linux-64=12.6.85
  - cuda-nvdisasm=12.6.77
  - cuda-nvml-dev=12.6.77
  - cuda-nvprof=12.6.80
  - cuda-nvprune=12.6.77
  - cuda-nvrtc=12.6.85
  - cuda-nvrtc-dev=12.6.85
  - cuda-nvtx=12.6.77
  - cuda-nvvm-dev_linux-64=12.6.85
  - cuda-nvvm-impl=12.6.85
  - cuda-nvvm-tools=12.6.85
  - cuda-nvvp=12.6.80
  - cuda-opencl=12.6.77
  - cuda-opencl-dev=12.6.77
  - cuda-profiler-api=12.6.77
  - cuda-runtime=12.6.3
  - cuda-sanitizer-api=12.6.77
  - cuda-toolkit=12.6.3
  - cuda-tools=12.6.3
  - cuda-version=12.6
  - cuda-visual-tools=12.6.3
  - dbus=1.16.2
  - expat=2.7.0
  - fontconfig=2.15.0
  - freetype=2.13.3
  - gcc_impl_linux-64=13.2.0
  - gcc_linux-64=13.2.0
  - gds-tools=1.11.1.6
  - gmp=6.3.0
  - gxx_impl_linux-64=13.2.0
  - gxx_linux-64=13.2.0
  - icu=75.1
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libcublas=12.6.4.1
  - libcublas-dev=12.6.4.1
  - libcufft=11.3.0.4
  - libcufft-dev=11.3.0.4
  - libcufile=1.11.1.6
  - libcufile-dev=1.11.1.6
  - libcurand=10.3.7.77
  - libcurand-dev=10.3.7.77
  - libcurl=8.13.0
  - libcusolver=11.7.1.2
  - libcusolver-dev=11.7.1.2
  - libcusparse=12.5.4.2
  - libcusparse-dev=12.5.4.2
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=13.2.0
  - libgcc-ng=15.1.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libiconv=1.18
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.6.77
  - libnvfatbin-dev=12.6.77
  - libnvjitlink=12.6.85
  - libnvjitlink-dev=12.6.85
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libpng=1.6.47
  - libsanitizer=13.2.0
  - libsqlite=3.49.2
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=13.2.0
  - libstdcxx-ng=15.1.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - ncurses=6.5
  - nsight-compute=2024.3.2.3
  - nspr=4.36
  - nss=3.111
  - openssl=3.5.0
  - pcre2=10.45
  - pip=25.1.1
  - pthread-stubs=0.4
  - python=3.11.12
  - readline=8.2
  - rhash=1.4.6
  - setuptools=80.8.0
  - sysroot_linux-64=2.17
  - tk=8.6.13
  - wheel=0.45.1
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zstd=1.5.7
  - pip:
      - aiobotocore==2.22.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.0
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - attrs==25.3.0
      - botocore==1.37.3
      - certifi==2025.4.26
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - comm==0.2.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - dacite==1.9.2
      - datasets==3.6.0
      - debugpy==1.8.14
      - decorator==5.2.1
      - dill==0.3.8
      - distlib==0.3.9
      - dotenv==0.9.9
      - einops==0.8.1
      - executing==2.2.0
      - fev==0.4.1
      - filelock==3.18.0
      - fonttools==4.58.0
      - frozenlist==1.6.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - gluonts==0.16.1
      - hf-xet==1.1.2
      - huggingface-hub==0.32.0
      - identify==2.6.12
      - idna==3.10
      - iniconfig==2.1.0
      - ipykernel==6.29.5
      - ipython==9.2.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joypy==0.2.6
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.8
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.3
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mlstm-kernels==2.0.0
      - mpmath==1.3.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nodeenv==1.9.1
      - numpy==2.1.3
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - opt-einsum==3.4.0
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - pluggy==1.6.0
      - pre-commit==4.2.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - pytorch-lightning==2.5.1.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - regex==2024.11.6
      - reportlab==4.4.1
      - requests==2.32.3
      - rich==14.0.0
      - s3fs==2025.3.0
      - safetensors==0.5.3
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - tirex==1.0.0
      - tokenizers==0.21.1
      - toolz==0.12.1
      - torch==2.6.0+cu126
      - torchaudio==2.6.0+cu126
      - torchmetrics==1.7.1
      - torchvision==0.21.0+cu126
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.52.3
      - triton==3.2.0
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.4.0
      - virtualenv==20.31.2
      - wcwidth==0.2.13
      - wrapt==1.17.2
      - xlstm==2.0.3
      - xxhash==3.5.0
      - yarl==1.20.0
